name: Enforce CHANGELOG Update
on:
  pull_request:
    branches:
      - master
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true   
jobs:
  check-changelog-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Verify changes in CHANGELOG file
        id: verify-changes
        run: |
          changelogPresent=false
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [ "$changed_file" == "CHANGELOG.md" ]; then
              changelogPresent=true
              break
            fi
          done
          echo "::set-output name=changelog-updated::$changelogPresent"
      - name: Check
        if: ${{ steps.verify-changes.outputs.changelog-updated }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('CHANGELOG has to be updated on pull request to master')
